# Generated by Django 6.0.5 on 2026-05-28 13:03

import django.db.models.deletion
import forum.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_notification_board_icon_reply_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('file', '文件')], max_length=16, verbose_name='类型')),
                ('file', models.FileField(upload_to=forum.models.attachment_upload_to, verbose_name='文件')),
                ('original_name', models.CharField(blank=True, max_length=200, verbose_name='原始文件名')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='文件大小')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='宽')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='高')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='链接')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('image', models.URLField(blank=True, max_length=500, verbose_name='封面图')),
                ('site_name', models.CharField(blank=True, max_length=100, verbose_name='站点名')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='抓取时间')),
            ],
            options={
                'verbose_name': '链接预览',
                'verbose_name_plural': '链接预览',
            },
        ),
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, '赞'), (-1, '踩')], verbose_name='投票')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '帖子投票',
                'verbose_name_plural': '帖子投票',
            },
        ),
        migrations.CreateModel(
            name='ReplyVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, '赞'), (-1, '踩')], verbose_name='投票')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '回帖投票',
                'verbose_name_plural': '回帖投票',
            },
        ),
        migrations.RemoveConstraint(
            model_name='postlike',
            name='unique_post_like_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='replylike',
            name='unique_reply_like_per_user',
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=forum.models.cover_upload_to, verbose_name='封面图'),
        ),
        migrations.AddField(
            model_name='post',
            name='hot_score',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='热度'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_nsfw',
            field=models.BooleanField(default=False, verbose_name='NSFW'),
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(db_index=True, default=0, verbose_name='得分（赞 - 踩）'),
        ),
        migrations.AddField(
            model_name='reply',
            name='score',
            field=models.IntegerField(default=0, verbose_name='得分'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=forum.models.avatar_upload_to, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('reply', '回复了你的帖子'), ('reply_to_reply', '回复了你的回帖'), ('post_like', '点赞了你的帖子'), ('reply_like', '点赞了你的回帖'), ('mention', '提到了你')], max_length=32, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='正文'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['board', '-is_pinned', '-hot_score'], name='forum_post_board_i_8b45c9_idx'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forum.post'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forum.reply'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='forum.post', verbose_name='帖子'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='postvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum.post', verbose_name='帖子'),
        ),
        migrations.AddField(
            model_name='postvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_votes', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='replyvote',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum.reply', verbose_name='回帖'),
        ),
        migrations.AddField(
            model_name='replyvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_votes', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='replylike',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='replylike',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_bookmark_per_user_post'),
        ),
        migrations.AddConstraint(
            model_name='postvote',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_post_vote_per_user'),
        ),
        migrations.AddConstraint(
            model_name='replyvote',
            constraint=models.UniqueConstraint(fields=('reply', 'user'), name='unique_reply_vote_per_user'),
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
        migrations.DeleteModel(
            name='ReplyLike',
        ),
    ]
