# Generated by Django 6.0.5 on 2026-05-28 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_boardmoderator_boardsubscription_conversation_follow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='forum.reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '回帖收藏',
                'verbose_name_plural': '回帖收藏',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'reply'), name='unique_reply_bookmark_per_user')],
            },
        ),
    ]
